# Generated by Django 5.0.4 on 2024-05-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoundSky', '0003_user_followed_user_followers_comment_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='Playlist',
            field=models.ManyToManyField(blank=True, to='SoundSky.playlist'),
        ),
    ]
