# Generated by Django 5.0.4 on 2024-05-23 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoundSky', '0004_song_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
