# Generated by Django 5.0.4 on 2024-05-23 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoundSky', '0010_alter_song_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='Playlist',
        ),
    ]
