# Generated by Django 5.0.4 on 2024-05-23 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoundSky', '0011_remove_song_playlist'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('user_being_followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='followed', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers_rel', to='SoundSky.followers')),
            ],
        ),
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('user_that_follows', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='followers', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('users_being_followed', models.ManyToManyField(blank=True, related_name='followed_rel', to='SoundSky.follows')),
            ],
        ),
    ]
