# Generated by Django 5.0.4 on 2024-05-23 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoundSky', '0012_followers_follows'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followers',
            options={'verbose_name_plural': 'Followers'},
        ),
        migrations.AlterModelOptions(
            name='follows',
            options={'verbose_name_plural': 'Follows'},
        ),
    ]
