# Generated by Django 5.0.4 on 2024-05-23 23:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoundSky', '0013_alter_followers_options_alter_follows_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers_rel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follows',
            name='users_being_followed',
            field=models.ManyToManyField(blank=True, related_name='followed_rel', to=settings.AUTH_USER_MODEL),
        ),
    ]
