# Generated by Django 5.0.4 on 2024-05-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoundSky', '0014_alter_followers_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='url',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default='audio_files/PabloPhonk.mp3', upload_to='audio_files/'),
        ),
    ]
