# Generated by Django 5.0.4 on 2024-05-24 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoundSky', '0015_remove_song_url_song_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_file',
        ),
    ]
