# Generated by Django 5.0.4 on 2024-05-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoundSky', '0016_remove_song_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default='SoundSky/media/audio_files/PabloPhonk.mp3', upload_to='audio_files/'),
        ),
    ]
