# Generated by Django 5.0.4 on 2024-05-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoundSky', '0019_remove_song_audio_file_song_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.URLField(),
        ),
    ]
